# Generated by Django 4.1.7 on 2023-02-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_vote_comment_post_comments_post_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
    ]
