# Generated by Django 4.1.7 on 2023-02-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_votes_count_alter_comment_post_alter_vote_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='votes_count',
        ),
    ]
