# Generated by Django 4.1.7 on 2023-02-20 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_alter_comment_post_alter_post_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='post_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='post_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
